### PR TITLE
Fix position of attribution link

### LINKED ISSUE #292: DuckPAN renders (i) icon incorrectly
image

I'm not sure why it's so poorly positioned?

### LINKED ISSUE #310: DuckDuckGo CSS Loading: force order to mimic DuckDuckGo.com
After a while of seeing various oddities with the UI when testing in DuckPAN I've realized that the cause is that we're loading the CCS files we pull down from DuckDuckGo in a different order than how they're loaded in production.

Seeing as order matters in CSS, certain rules aren't overriding each other, causing some visual discrepancies.

We need to ensure the CSS are concatenated in the same order that they appear on DuckDuckGo. As a test, I manually dropped the current CSS links into a DuckPAN window and the UI corrected itself

### PR DESCRIPTION
**Pull request by Mailkov**
Fixes #310 & Fixes #292

### CODE REVIEW

File: lib/App/DuckPAN/Cmd/Server.pm [hunk 1]
```diff
@@ -355,21 +355,26 @@ sub get_sub_assets {
...
-				  {
-					name     => $name . ' CSS',
-					internal => $cache_path->child($name),
-					external => $name
-				  };
+				push @cssfile, $name;
 			}
 		}
 	}
+    foreach (sort @cssfile) {
```
Comment (moollaza) [inline lib/App/DuckPAN/Cmd/Server.pm]: Looks like there's mixed tabs & spaces?

This file uses hard-tabs, so lets stick with those

**Comment by moollaza** [comment]
@Mailkov Thanks! This LGTM :+1:
